export const FILTERED_MESSAGE = 'FILTERED_MESSAGE'
export const FETCH_MEMBERS = 'FETCH_MEMBERS'
export const CURRENT_MEMBER = 'CURRENT_MEMBER'

export const SEND_MESSAGE = 'SEND_MESSAGE'
export const GET_MESSAGE = 'GET_MESSAGE'